# Generated by Django 3.2.5 on 2022-05-13 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conmment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=255, verbose_name='댓글')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
    ]
